#!/usr/local/bin/python3.10
import string
import sys

if len(sys.argv) < 2:
    exit('No file provided')
else:
    FILENAME = sys.argv[1]

ab = list(string.ascii_uppercase) + [' ']

with open(FILENAME, 'r') as f:
    pv = [list(x.split('-')[0].upper()) for x in f.read().split('\n') if len(x) > 0]
    pv = [[y for y in x if y in ab] for x in pv]
    pv = [''.join(x) for x in pv]

with open(FILENAME, 'w+') as f:
    f.write('\n'.join(pv))
